name: Kingdoms
version: 1.6
main: com.excrele.kingdoms.KingdomsPlugin
api-version: 1.21
commands:
  kingdom:
    description: Manage kingdoms
    usage: /<command> <subcommand>
    aliases: [k]
  kc:
    description: Kingdom chat
    usage: /<command> <message>
    aliases: [kingdomchat]
  levelup:
    description: Level up your kingdom
    usage: /<command>
permissions:
  kingdoms.admin:
    description: Allows admin commands
    default: op